/* automatically generated by rust-bindgen 0.57.0 */

extern "C" {
    pub fn f() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn g(
        arg1: ::std::os::raw::c_int,
        arg2: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
